[package]
name = "mouseshare-net"
version = "0.1.0"
edition = "2021"

[dependencies]
mouseshare-protocol = { path = "../protocol" }
tokio = { version = "1", default-features = false, features = ["net", "io-util"] }
thiserror = "1"
tracing = "0.1"

[dev-dependencies]
tokio = { version = "1", default-features = false, features = ["net", "io-util", "rt", "macros", "time"] }
