//! (key, English, Simplified Chinese). `{0}`, `{1}` ... are placeholders and
//! must appear in both languages (checked by a unit test in `i18n.rs`).

pub const TABLE: &[(&str, &str, &str)] = &[
    // --- common ---
    ("add", "Add", "添加"),
    ("cancel", "Cancel", "取消"),
    ("close", "Close", "关闭"),
    ("back", "Back", "上一步"),
    ("next", "Next", "下一步"),
    ("skip", "Skip", "跳过"),
    ("copy", "Copy", "复制"),
    ("copied", "Copied", "已复制"),
    ("remove", "Remove", "移除"),
    ("start", "Start sharing", "开始共享"),
    ("stop", "Stop sharing", "停止共享"),
    ("settings", "Settings", "设置"),
    ("log", "Log", "日志"),
    ("version", "Version", "版本"),
    ("you", "you", "本机"),
    ("status", "Status", "状态"),
    ("port", "Port", "端口"),
    ("address", "Address", "地址"),
    // --- top bar ---
    ("pill_active", "Sharing", "共享中"),
    ("pill_idle", "Not sharing", "未共享"),
    ("pill_error", "Error", "出错"),
    // --- roles / rail ---
    ("role_controller", "Control", "控制端"),
    ("role_target", "Controlled", "被控端"),
    (
        "role_controller_hint",
        "This computer has the mouse and keyboard.",
        "这台电脑拥有鼠标和键盘。",
    ),
    (
        "role_target_hint",
        "Another computer's mouse and keyboard will drive this one.",
        "由另一台电脑的鼠标和键盘来操作这台电脑。",
    ),
    ("devices", "Devices", "设备"),
    ("add_device", "Add device", "添加设备"),
    (
        "select_hint",
        "Select a device to edit its address, pairing code and pointer speed.",
        "选择一台设备，可编辑它的地址、配对码和指针速度。",
    ),
    ("this_computer", "This computer", "这台电脑"),
    ("device_name", "Device name", "设备名称"),
    ("monitors", "Monitors", "显示器"),
    ("monitors_unknown", "Monitors not detected yet", "尚未检测到显示器"),
    ("monitors_n", "{0} monitors · {1}", "{0} 个显示器 · {1}"),
    ("remove_device", "Remove device", "移除设备"),
    ("address_hint", "192.168.1.20:7878 (blank = find automatically)", "192.168.1.20:7878（留空则自动查找）"),
    ("address_optional", "Address (optional)", "地址（可选）"),
    ("pairing_code", "Pairing code", "配对码"),
    ("code_ok", "Code looks good", "配对码格式正确"),
    ("code_missing", "Enter the code shown on that computer", "请输入那台电脑上显示的配对码"),
    ("code_invalid", "That is not a valid pairing code", "配对码格式不正确"),
    ("code_where", "Shown on the other computer after choosing “Controlled”.", "在另一台电脑上选择“被控端”后即可看到。"),
    ("pointer_speed", "Pointer speed", "指针速度"),
    ("align", "Align", "对齐"),
    ("align_top", "Top", "顶部"),
    ("align_middle", "Middle", "居中"),
    ("align_bottom", "Bottom", "底部"),
    ("align_left", "Left", "左对齐"),
    ("align_center", "Center", "居中"),
    ("align_right", "Right", "右对齐"),
    (
        "hint_idle_controller",
        "Arrange your screens, then start sharing.",
        "排好屏幕位置后，点击开始共享。",
    ),
    (
        "hint_idle_target",
        "Start sharing and enter the pairing code on the controller.",
        "开始共享，并在控制端输入配对码。",
    ),
    (
        "hint_running_controller",
        "{0} of {1} connected · {2} returns to this computer",
        "已连接 {0}/{1} · 按 {2} 可回到本机",
    ),
    // --- canvas ---
    ("canvas_overlap", "Screens overlap — drag them apart", "屏幕重叠了，请拖开"),
    ("zoom_in", "Zoom in", "放大"),
    ("zoom_out", "Zoom out", "缩小"),
    ("zoom_fit", "Fit to view", "适应窗口"),
    ("cursor_here", "Cursor here", "光标在此"),
    // --- statuses ---
    ("st_not_connected", "Not connected", "未连接"),
    ("st_connecting", "Connecting…", "连接中…"),
    ("st_connected", "Connected", "已连接"),
    ("st_connected_ms", "Connected · {0} ms", "已连接 · {0} 毫秒"),
    ("st_wrong_code", "Wrong pairing code", "配对码错误"),
    ("st_retrying", "Unreachable, retrying…", "无法连接，正在重试…"),
    // --- errors ---
    ("err_no_devices", "Add at least one device to control first.", "请先添加至少一台要控制的设备。"),
    ("err_overlap", "Some screens overlap. Drag them apart first.", "有屏幕重叠，请先把它们拖开。"),
    ("err_no_code", "Enter the pairing code for “{0}”.", "请输入“{0}”的配对码。"),
    ("err_bad_addr", "The address of “{0}” ({1}) is not valid.", "“{0}”的地址（{1}）格式不正确。"),
    ("err_dup_name", "A device with that name already exists.", "已存在同名设备。"),
    ("err_addr_format", "Use the form 192.168.1.20:7878", "格式应为 192.168.1.20:7878"),
    // --- toasts ---
    ("toast_copied", "Copied to clipboard", "已复制到剪贴板"),
    ("toast_connected", "{0} connected", "{0} 已连接"),
    ("toast_lost", "Lost connection to {0}", "与 {0} 的连接已断开"),
    ("toast_auth", "{0} rejected the pairing code", "{0} 拒绝了配对码"),
    ("toast_ctrl_in", "{0} is now controlling this computer", "{0} 正在控制这台电脑"),
    ("toast_ctrl_out", "{0} disconnected", "{0} 已断开"),
    ("toast_rejected", "Refused a connection from {0}", "已拒绝来自 {0} 的连接"),
    ("toast_hotkey", "Returned to this computer", "已回到本机"),
    // --- target view ---
    ("target_title", "This computer can be controlled", "这台电脑可以被控制"),
    (
        "target_sub",
        "Enter this code on the computer that has the mouse and keyboard.",
        "在拥有鼠标和键盘的那台电脑上输入此配对码。",
    ),
    ("new_code", "New code", "换新码"),
    ("stop_first", "Stop sharing first", "请先停止共享"),
    ("target_stopped", "Not sharing", "未共享"),
    ("target_waiting", "Waiting for a controller…", "等待控制端连接…"),
    ("target_controlled_by", "Controlled by {0}", "正由 {0} 控制"),
    ("target_steps_title", "HOW TO PAIR", "配对步骤"),
    ("target_step1", "Press “Start sharing” here.", "在这里点击“开始共享”。"),
    ("target_step2", "On the other computer choose “Control” and add this device.", "在另一台电脑上选择“控制端”，添加这台设备。"),
    ("target_step3", "Type the code above, then drag the screens into place.", "输入上面的配对码，然后拖动屏幕摆放位置。"),
    // --- add / remove dialogs ---
    (
        "add_sub",
        "Pick a computer found on your network or enter its details.",
        "选择网络中发现的电脑，或手动填写信息。",
    ),
    ("found_on_lan", "Found on your network", "在网络中发现"),
    ("rescan", "Scan again", "重新扫描"),
    ("scanning", "Scanning…", "正在扫描…"),
    (
        "none_found",
        "Nothing found. Make sure the other computer is sharing, or enter its address.",
        "没有发现设备。请确认另一台电脑已开始共享，或手动输入地址。",
    ),
    ("remove_title", "Remove “{0}”?", "移除“{0}”？"),
    (
        "remove_body",
        "Its pairing code is forgotten. You can add it again at any time.",
        "将忘记它的配对码，之后可以随时重新添加。",
    ),
    // --- settings ---
    ("tab_general", "General", "常规"),
    ("tab_input", "Input", "输入"),
    ("tab_clipboard", "Clipboard", "剪贴板"),
    ("tab_security", "Security", "安全"),
    ("tab_about", "About", "关于"),
    (
        "apply_on_restart",
        "Changes to input, clipboard and security apply the next time you start sharing.",
        "输入、剪贴板和安全方面的更改会在下次开始共享时生效。",
    ),
    ("language", "Language", "语言"),
    ("lang_auto", "Automatic", "自动"),
    ("theme", "Theme", "主题"),
    ("theme_auto", "Auto", "自动"),
    ("theme_dark", "Dark", "深色"),
    ("theme_light", "Light", "浅色"),
    ("accent", "Accent colour", "强调色"),
    ("ui_scale", "Interface size", "界面大小"),
    ("autostart", "Open at login", "登录时自动打开"),
    ("autostart_hint", "Starts mouseshare when you sign in.", "登录系统时自动启动 mouseshare。"),
    ("start_on_launch", "Start sharing on launch", "启动后自动开始共享"),
    (
        "start_on_launch_hint",
        "No need to press Start every time.",
        "不必每次都手动点击开始。",
    ),
    ("show_welcome", "Show the welcome guide again", "重新显示欢迎引导"),
    ("hotkey", "Return hotkey", "返回快捷键"),
    (
        "hotkey_hint",
        "Brings the cursor back to this computer, e.g. Ctrl+Alt+Esc.",
        "把光标拉回本机，例如 Ctrl+Alt+Esc。",
    ),
    ("edge_dwell", "Edge delay", "边缘停留时间"),
    (
        "edge_dwell_hint",
        "How long the cursor must push against an edge before switching.",
        "光标需在屏幕边缘停留多久才会切换设备。",
    ),
    ("hold_guard", "Don’t switch while dragging", "拖拽时不切换"),
    (
        "hold_guard_hint",
        "Ignore edges while a mouse button is held.",
        "按住鼠标按键时忽略屏幕边缘。",
    ),
    ("natural_scroll", "Natural scrolling", "自然滚动"),
    (
        "natural_scroll_hint",
        "Reverse the wheel direction on controlled computers.",
        "反转被控电脑上的滚轮方向。",
    ),
    ("clip_sync", "Share clipboard text", "共享剪贴板文本"),
    (
        "clip_sync_hint",
        "Copy on one computer, paste on another.",
        "在一台电脑上复制，在另一台上粘贴。",
    ),
    ("clip_max", "Size limit", "大小上限"),
    (
        "clip_max_hint",
        "Larger clips are not sent.",
        "超过上限的内容不会被发送。",
    ),
    ("sec_title", "Encrypted and paired", "加密并配对"),
    (
        "sec_body",
        "Every connection is authenticated with the pairing code and encrypted end to end. Only computers that know the code can control this one.",
        "每条连接都用配对码认证并端到端加密，只有知道配对码的电脑才能控制这台电脑。",
    ),
    ("sec_own_code", "This computer’s code", "本机配对码"),
    (
        "sec_own_code_hint",
        "Controllers must enter this to control this computer.",
        "控制端需要输入它才能控制这台电脑。",
    ),
    ("port_hint", "Port used when this computer is controlled.", "本机被控制时使用的端口。"),
    (
        "about_body",
        "Share one mouse, keyboard and clipboard across your computers over the local network.",
        "在局域网内的多台电脑之间共享同一套鼠标、键盘和剪贴板。",
    ),
    ("about_license", "Released under the MIT license.", "以 MIT 许可证发布。"),
    // --- onboarding ---
    ("ob_welcome", "Welcome to mouseshare", "欢迎使用 mouseshare"),
    (
        "ob_welcome_sub",
        "Use one mouse and keyboard across several computers. Setup takes about a minute.",
        "用一套鼠标键盘操作多台电脑，设置只需一分钟。",
    ),
    ("ob_name_q", "What should this computer be called?", "给这台电脑起个名字"),
    (
        "ob_name_hint",
        "Other computers will see this name.",
        "其他电脑会看到这个名字。",
    ),
    ("ob_role_title", "What will this computer do?", "这台电脑负责什么？"),
    (
        "ob_role_sub",
        "You can change this at any time.",
        "之后可以随时更改。",
    ),
    ("ob_role_ctrl", "Control other computers", "控制其他电脑"),
    (
        "ob_role_ctrl_body",
        "This one has the mouse and keyboard. Move the cursor off the screen edge to drive another computer.",
        "这台电脑有鼠标和键盘。把光标移出屏幕边缘，就能操作另一台电脑。",
    ),
    ("ob_role_target", "Be controlled", "被其他电脑控制"),
    (
        "ob_role_target_body",
        "Another computer’s mouse and keyboard will drive this one. You get a pairing code to enter there.",
        "由另一台电脑的鼠标键盘来操作这台电脑，你会得到一个配对码，在那边输入。",
    ),
    ("ob_ready", "You’re all set", "一切就绪"),
    (
        "ob_ready_ctrl",
        "Add the computers you want to control, arrange their screens, and press Start sharing.",
        "添加要控制的电脑，摆好屏幕位置，然后点击开始共享。",
    ),
    (
        "ob_ready_target",
        "Press Start sharing, then enter the pairing code on the controlling computer.",
        "点击开始共享，然后在控制端输入配对码。",
    ),
    (
        "ob_tip_hotkey",
        "If the cursor ever gets stuck on another computer, press {0}.",
        "如果光标卡在另一台电脑上，请按 {0}。",
    ),
    (
        "ob_tip_settings",
        "Themes, hotkey, clipboard and more are in Settings.",
        "主题、快捷键、剪贴板等选项都在“设置”里。",
    ),
    ("ob_finish_ctrl", "Add a device", "添加设备"),
    ("ob_finish_target", "Get started", "开始使用"),
];
